version: '3.3'
services:
  vault:
    image: hashicorp/vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
    ports:
      - "8200:8200"
      - "8201:8201"
    restart: always
    cap_add:
      - IPC_LOCK
